In [1]:
# Numpy means numerical python it is complete mathematical package. It has crated for array amd matrix manipulation

In [2]:
import numpy as np

In [3]:
l = [1,2,3,4,5]

In [4]:
# Converting list to array

arr = np.array(l)

In [5]:
arr

array([1, 2, 3, 4, 5])

In [6]:
type(arr)

numpy.ndarray

In [7]:
# type is ndarray which is n dimensional array

In [8]:
np.asarray(l)  # With this also we can create an array

array([1, 2, 3, 4, 5])

In [9]:
arr1 = np.array([[1,2,3], [4,5,6]])  # It will convert this array into 2 dimensional array

In [10]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
# Checking dimension of arr

arr1.ndim

2

In [12]:
# Visualization of 2d-array

# on x axis col. number and on y axis row no.

# 1,2,3 will be on row 0 and 4,5,6 on row 1 and there will be 3 cols.

In [13]:
# matrix function

m1 = np.matrix(l)

In [14]:
m1

matrix([[1, 2, 3, 4, 5]])

In [15]:
m1.ndim

2

In [16]:
# matrix will be of min 2 dimension but array can also be 1 dimension

In [17]:
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [18]:
# If we pass matrix in this function

np.asanyarray(m1)

matrix([[1, 2, 3, 4, 5]])

In [19]:
# No change because asanyarray will convert it to array but as matrix is form of array so it will remain same 

In [20]:
arr

array([1, 2, 3, 4, 5])

# Swallow copy operation

In [27]:
a = arr

In [28]:
a

array([100,   2,   3,   4,   5])

In [29]:
arr

array([100,   2,   3,   4,   5])

In [33]:
arr[0] = 100  # Change in arr will also change a

In [34]:
arr

array([100,   2,   3,   4,   5])

In [35]:
a

array([100,   2,   3,   4,   5])

In [36]:
b = np.copy(arr)

In [37]:
b

array([100,   2,   3,   4,   5])

In [38]:
# If we made chage in b it will not change arr

b[0] = 500

In [39]:
arr

array([100,   2,   3,   4,   5])

In [42]:
np.fromfunction(lambda i,j : i==j, (3,3))  # 3,3 is shape we have give

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [43]:
np.fromfunction(lambda i,j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [44]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [45]:
iterable = (i*i for i in range(5))

In [47]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [48]:
np.fromstring('23 45 56', sep = ' ')

array([23., 45., 56.])

In [49]:
np.fromstring('23,45,56', sep = ',')

array([23., 45., 56.])

# Numpy Functions

In [50]:
arr

array([100,   2,   3,   4,   5])

In [51]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
arr.ndim

1

In [53]:
arr.size

5

In [54]:
arr.shape

(5,)

In [55]:
arr1.shape

(2, 3)

In [56]:
arr.dtype

dtype('int64')